name: Create Release
description: Create git tag and GitHub release

inputs:
  version:
    description: "Version to release (without v prefix)"
    required: true

runs:
  using: composite
  steps:
    - name: Create tag
      shell: bash
      env:
        TAG: v${{ inputs.version }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag "$TAG"
        git push origin "$TAG"

    - name: Create GitHub release
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        TAG: v${{ inputs.version }}
      run: gh release create "$TAG" --generate-notes
