name: Elixir Setup
description: Set up Elixir/OTP, cache, and install dependencies

inputs:
  otp-version:
    description: "OTP version"
    default: "27"
  elixir-version:
    description: "Elixir version"
    default: "1.18"

runs:
  using: composite
  steps:
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ inputs.otp-version }}
        elixir-version: ${{ inputs.elixir-version }}

    - name: Restore dependencies cache
      uses: actions/cache@v5
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      shell: bash
      run: mix deps.get
